### ISSUE TITLE
Add labelling of resources

### ISSUE THREAD

**Issue by fzdarsky** [flightctl/flightctl#16]
Allow to CRUD labels for all resources

**Comment by avishayt** [comment]
k8s API:

I1227 20:44:36.867155 3380843 request.go:1188] Request Body: {"metadata":{"labels":{"foo":"bar"}}}
I1227 20:44:36.867196 3380843 round_trippers.go:466] curl -v -XPATCH  -H "Content-Type: application/merge-patch+json" -H "Accept: application/json" -H "User-Agent: kubectl/v1.27.3 (linux/amd64) kubernetes/25b4e43" 'https://127.0.0.1:39737/api/v1/namespaces/kube-system/pods/coredns-5d78c9869d-k2zbw?fieldManager=kubectl-label'
I1227 20:44:36.939572 3380843 round_trippers.go:553] PATCH https://127.0.0.1:39737/api/v1/namespaces/kube-system/pods/coredns-5d78c9869d-k2zbw?fieldManager=kubectl-label 200 OK in 72 milliseconds
