### ISSUE TITLE
Agent TPM logic 

### ISSUE THREAD

**Issue by hexfusion** [flightctl/flightctl#170]
per @mangelajo  via #168 
> I suspect we should try to default to /dev/tpm0 or the right one... if it fails for no tpm may be the user can disable it.

This issue tracks this conversation.

ref. https://github.com/flightctl/flightctl/blob/05171708737ba6d42238ecb103291a625446be11/internal/agent/agent.go#L87-L100

**Comment by fzdarsky** [comment]
In general, yes, let's choose sane defaults, e.g. `/dev/tpmrm0` (i.e. the resource-managed i/f) and fail with error if that cannot be used. Then add an explicit `--disable-tpm` flag for systems where TPM isn't available or during development.

**Comment by hexfusion** [comment]
this code no longer exists
