### ISSUE TITLE
Trying to build a bootc image on github CI fails

### ISSUE THREAD

**Issue by mangelajo** [flightctl/flightctl#193]
https://github.com/flightctl/flightctl/pull/191/checks#step:14:9162

```
Storing signatures
STEP 2/6: COPY bin/rpm/flightctl-agent-*.rpm /tmp/
time="2024-03-20T13:40:59Z" level=error msg="error unmounting /var/lib/containers/storage/overlay/c57e3aeaedd197b368d7f3d3f851ab89f70d59277c05347ae22fd7a92d4577d6/merged: invalid argument"
Error: error committing container for step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:copy Args:[bin/rpm/flightctl-agent-*.rpm /tmp/] Flags:[] Attrs:map[] Message:COPY bin/rpm/flightctl-agent-*.rpm /tmp/ Original:COPY bin/rpm/flightctl-agent-*.rpm /tmp/}: error copying layers and metadata for container "55d458d140739b91f73ef47da4f7b7969a5930b0e1a338c4298f048f6f9646eb": initializing source containers-storage:centos-bootc-working-container: error extracting layer "b728bf56150970d626f68f1982bb3ff0ed38ff998d53562b326e2785e4cda710": cannot mount layer, mount label "" too large 4233 > page size 4096
```

https://github.com/flightctl/flightctl/pull/191/checks#step:14:9162

https://github.com/flightctl/flightctl/blob/main/hack/Containerfile.local

**Comment by cgwalters** [comment]
Right so today our base image has a number of base layers.  I've seen people hit this when they have a *lot* of `RUN` invocations creating separate layers - and the usual fix is to squash those.

However in your case you have a really tiny set of layers.

It looks like you're building with podman...but what *version* of podman?  My experience with Github Actions is that the version there is *extremely* old.  I did a hack somewhere else where I pulled in a newer version, can try to dig it up.

**Comment by cgwalters** [comment]
It should work to build with docker, which is kept up to date a bit better.  (Other workarounds include doing the container build inside a privileged container with a newer podman/buildah, or using a self-hosted runner that isn't an ancient Ubuntu install, etc.)

**Comment by mangelajo** [comment]
It's the github CI default stock podman, probably old, we had this in the past:

https://github.com/flightctl/flightctl/commit/47a63be375d017ec707974b181eb62c4d8b3c71f#diff-94976da54d666308eb7e326703d54ce5a6268f37059f2da567ca3df12cbcb8c3L28


I will try with a newer version or docker and report back, thanks @cgwalters

**Comment by mangelajo** [comment]
Ok, I can confirm that docker from the ubuntu image works, and podman4 also works.

Thanks again!

**Comment by cgwalters** [comment]
I actually happened to be reviewing a PR and saw this go by https://github.com/osbuild/bootc-image-builder/pull/291/files#diff-1db27d93186e46d3b441ece35801b244db8ee144ff1405ca27a163bfe878957fR81

**Comment by mohan-shash** [comment]
@cgwalters given this being closed, do we still want to mention this in the Docs "known issues"?
