### ISSUE TITLE
"OverlappingSelectors" fleet condition is misleading

### ISSUE THREAD

**Issue by celdrake** [flightctl/flightctl#261]
I set-up two fleets:

1.  [eu-east-prod-001](https://github.com/celdrake/flightctl-demos/blob/multiple-owners/inverter-fleet/fleets/eu-east-prod-001/fleet.yaml): This fleet has a  `first-label=east` label
2. [eu-west-prod-001](https://github.com/celdrake/flightctl-demos/blob/multiple-owners/inverter-fleet/fleets/eu-west-prod-001/fleet.yaml): This fleet has a `second-label=west` label

Then I created an enrollment request, and approved this with the labels:
`first-label=east` and `second-label=west`

The device was correctly given the annotation for `MultipleOwners` and the two matching fleets are included on it.
However, both fleets are marked with the condition `OverlappingSelectors` though in reality there's no overlap in either of the fleet's labels.

Pointing to the overlap in the fleet labels is misleading, as the problem in caused by the device and not on the Fleets. 

Maybe we need a different Fleet condition annotation for a case like this ? Ideally, users should be told which device(s) are causing the problem .

**Comment by avishayt** [comment]
The intent is that the selectors overlap in their device selection - both fleets have at least one device in common.  There's also an annotation placed on the device which we could consider making a Condition.  But I don't think we can really say if the problem is caused by a fleet or a device.  For example we can have fleet1 with selectors region=US,state=NY and region=US,state=CA which is totally legal.

**Comment by celdrake** [comment]
> The intent is that the selectors overlap in their device selection - both fleets have at least one device in common. There's also an annotation placed on the device which we could consider making a Condition. But I don't think we can really say if the problem is caused by a fleet or a device. For example we can have fleet1 with selectors region=US,state=NY and region=US,state=CA which is totally legal.

The message for this error in particular is not accurate: "Fleet's selector overlaps with at least one other fleet, causing ambiguous device ownership"
I understand it's not always easy to discriminate, but in the above example, the fleets selectors have no overlaps. That's why I wonder if we could have two cases, depending on whether or not there is overlap in the fleets' selectors.

Anyway, I think the proper solution will come when we can create actions to fix these type of issues. We should be able to pinpoint where the overlap is, so users can understand how to fix it.

**Comment by celdrake** [comment]
Adddressed via Jira tickets.
